baseURL = "https://tomkenta.github.io"
languageCode = "en-us"
title = "tomkenta"
theme = "hugo-theme-hello-friend-tk"

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpired = false
canonifyURLs = true

[author]
  name = "tomkenta"

[params]

  homeSubtitle = "Full stack web developer"

  [params.logo]
    logoText     = "cd ~ "
    logoHomeLink = "/"
    # Set true to remove the logo cursor entirely.
    # logoCursorDisabled = false
    # Set to a valid CSS color to change the cursor in the logo.
    # logoCursorColor    = "#67a2c9"
    # Set to a valid CSS time value to change the animation duration, "0s" to disable.
    # logoCursorAnimate  = "2s"

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/tomkenta"

  [[params.social]]
    name = "github"
    url  = "https://github.com/tomkenta"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/kenta-yokota/"

  [[params.social]]
    name = "qiita"
    url  = "https://qiita.com/tomkenta"

 [[params.social]]
    name = "reddit"
    url  = "https://www.reddit.com/user/tomkenta"
  
[menu]

  [[menu.main]]
    identifier = "whois"
    name       = "whois tomkenta"
    url        = "/whois-tomkenta"
    weight     = 1

  [[menu.main]]
    identifier = "blog"
    name       = "blog"
    url        = "https://blog.tomkenta.com"
    weight     = 2
