baseURL = "https://tomkenta.github.io"
languageCode = "en-us"
title = "Welecome, tomkenta's page"
theme = "hugo-theme-hello-friend-tk"

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpired = false
canonifyURLs = true


[params]

  [params.logo]
    logoText     = "$tomkenta@github.io cd ~ "
    logoHomeLink = "/"
    # Set true to remove the logo cursor entirely.
    # logoCursorDisabled = false
    # Set to a valid CSS color to change the cursor in the logo.
    # logoCursorColor    = "#67a2c9"
    # Set to a valid CSS time value to change the animation duration, "0s" to disable.
    # logoCursorAnimate  = "2s"

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/tomkenta"

  [[params.social]]
    name = "github"
    url  = "https://github.com/tomkenta"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/kenta-yokota/"

[menu]
  [[menu.main]]
    identifier = "blog"
    name       = "blog"
    url        = "https://blog.tomkenta.com"
  [[menu.main]]
    identifier = "about"
    name       = "about"
    url        = "/about"
